"""empty message

Revision ID: 44a2c72c3478
Revises: 7b6461c5f7a6
Create Date: 2024-09-16 21:01:56.731641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a2c72c3478'
down_revision = '7b6461c5f7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.String(length=11), nullable=False),
    sa.Column('user_id', sa.String(length=11), nullable=False),
    sa.Column('score', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('quiz_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=11),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'quizzes', ['quiz_id'], ['id'])
        batch_op.alter_column('quiz_id',
               existing_type=sa.String(length=11),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_table('results')
    # ### end Alembic commands ###
