"""empty message

Revision ID: 7b6461c5f7a6
Revises: 0fad92fe4b92
Create Date: 2024-09-16 19:00:02.483043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b6461c5f7a6'
down_revision = '0fad92fe4b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('optionA', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('optionB', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('optionC', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('optionCorrect', sa.String(length=2), nullable=False))
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('optionCorrect')
        batch_op.drop_column('optionC')
        batch_op.drop_column('optionB')
        batch_op.drop_column('optionA')
        batch_op.drop_column('question')

    # ### end Alembic commands ###
